### PR TITLE
Editing README.md file explaining about Features,Getting Started,Cont…

### PR DESCRIPTION
**Pull request by shivamsinghrajputcse**
Subject: [Pull Request] Added README.md file

Hi Debasish Biswas,

I hope this message finds you well. I have made some contributions to the project by adding the README.md file. This file provides an overview of the project, its features, and guidelines for contributing. It aims to make it easier for users and potential contributors to understand the purpose of the project and get started with their contributions.

Here is a summary of the changes I made:

- Created README.md file
- Provided an introduction to the project
- Listed the features of the web API
- Explained how to get started with contributing
- Outlined the future roadmap for the project
- Added a license section and contact information

I believe that this contribution will greatly benefit the project by providing essential information to users and potential contributors. It will improve the project's visibility, encourage community engagement, and attract more contributors.

Please review the changes and let me know if any further modifications or additions are required. I'm open to feedback and eager to work collaboratively to enhance the project.

Thank you for your time and consideration.

Best regards,
Shivam Singh

### CODE REVIEW

**Review by Flanker-shyam — APPROVED** [review]

**Review by debasishbsws — APPROVED** [review]
Looks Good to me For now.
I think We also need a very easy guide for people who don't know GitHub to submit their Question Papers via GitHub Pull request.
something like https://linkfree.io/docs/quickstart

**Comment by debasishbsws** [comment]
Thank You for contributing.

**Comment by Flanker-shyam** [comment]
> Looks Good to me For now. I think We also need a very easy guide for people who don't know GitHub to submit their Question Papers via GitHub Pull request. something like https://linkfree.io/docs/quickstart

Will add that soon, after adding a little work on posting part.

**Comment by shivamsinghrajputcse** [comment]
Thank you for giving me this opportunity

**Pull request merged**
